---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age194jghefqry2nlk8klxy75ap4y5ljdm7gsh6fdw6pdy262vm6ee9qxfmuq6"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age194jghefqry2nlk8klxy75ap4y5ljdm7gsh6fdw6pdy262vm6ee9qxfmuq6"
stores:
  yaml:
    indent: 2
