# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:vOnkUrRM5xg2LfdNGg8Qd5svpzhveSJRakMRTSUSvhw=,iv:y6wXN/qapovtGc8kItvSCUMauxNuJcZbCNzMiXsfsnE=,tag:LD2tZ3mAiVGv36ncXLffOQ==,type:str]
sops:
  age:
    - recipient: age194jghefqry2nlk8klxy75ap4y5ljdm7gsh6fdw6pdy262vm6ee9qxfmuq6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWm9yS3NFVTZ0Tmp5c0Fk
        emlxSTVuM05pTlBaN042QnFIUnNhQ0tHeVFZClFOTmVsaXI4UEhkOXBiNitmY1VR
        VUxhSm83R29qdk04SkwxQ3BTSmRhZGcKLS0tIE4zU3lOTEJDeWtGUUlYUUZVNWZD
        eENDeFFYRVBiS2JSb1VuN1R6dmhYa0EKLJ27I3Jzt3p6XWzucpBwNa8Po5Qst01O
        3k7ShcejVEl5q3Afpm3c7ul2DUNLltT+9RFxDaAYXDLyZbgjpyyFng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-07T23:00:08Z"
  mac: ENC[AES256_GCM,data:Mr0DbfYWVzyJIh/ouDQmxyJnbv7MwlXCRCEis3YyHralQA3ebgO/f/+11gDnnAAj6P+dHAQfwBrI0egVPFlgh8qmVFBLIKjq2ZsIR4VzZFm4AbrQWFbo0Z0moLQleF9VaepWrH2tGLcqsIAZ9iYA2hL6nM6xdWmXmbyx8mZwOos=,iv:PYWhAHmU8wZcw7G5lTfYgLL+123COsaqFxSnoUuOHWU=,tag:lEJAnj/8gJUaXMQFqPiUcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
