# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:iHggFcbjmE+yY8MtdOVrfKTHXRPLSaIIF3+KTCFqBUcDHPY5V3JZtQ==,iv:Diq+jywhbd/eU8Ux3xdBz9X7XNpzL3ejBhhaFHb6284=,tag:CA4Ov0MALL+9drDa9hV8Tg==,type:str]
sops:
  age:
    - recipient: age194jghefqry2nlk8klxy75ap4y5ljdm7gsh6fdw6pdy262vm6ee9qxfmuq6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Vi9UOG5OQS9XY1FYVHBh
        cW1qUG15T1VwQTVoRWJYMGhtUnB6MVZqUVJzCmYyaFdXTm1wdDkvNFhVN0ZiME5o
        VlB0bTN5UlVlbFBOcmlYYWdLRENtV0kKLS0tIDc0VUgzZkxPT25NWkJ4TEpOUG5s
        Uk56bmZpQjl5bzVpejFSQWdNeWMvSTQKlHvnLbTcvUbjF5gmzvBAot0VxY4M+wfb
        66OteTIYHBIS8qday+bJhsGPnNaKW5I19DmUthL7Zn8blzN8BWiE1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-07T23:00:08Z"
  mac: ENC[AES256_GCM,data:SCZgqfe0/XsefSZRNXnSsRsoimX4pPaJXYHwVjfzo2hSgeva5R6Fdbp6JsQg4AhAuE4lFL75SkjTJBx8sfnnUsK3aLv4mBJFMT2b81enF25DELL01viCnJJRu88y/8tSx5z7OC0Hbi2Ylzuwwa4NE4l1Dc1hZ6CvUmBLOgJXMLI=,iv:k1gV72FRPKaHWg1XM9YRI4c2gur0xlDBXaZs3w7YmFU=,tag:DXe1hYH1JnY7yWsxV8yJyA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
